// src/types/taxTypes.ts
// TypeScript interfaces for Tax Settings functionality

/**
 * Tax Settings entity - tenant-specific tax configuration
 */
export interface TaxSettings {
  id: string;
  tenant_id: string;
  display_mode: 'including_tax' | 'excluding_tax' | 'no_tax';
  default_tax_rate_id: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

/**
 * Tax Rate entity - individual tax rates for a tenant
 */
export interface TaxRate {
  id: string;
  tenant_id: string;
  name: string;
  rate: number;
  is_default: boolean;
  is_active: boolean;
  sequence_no: number;
  description: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

/**
 * Tax Settings response - combines settings and rates
 */
export interface TaxSettingsResponse {
  settings: TaxSettings;
  rates: TaxRate[];
}

/**
 * Request payload for creating/updating tax settings
 */
export interface TaxSettingsRequest {
  display_mode: 'including_tax' | 'excluding_tax' | 'no_tax';
  default_tax_rate_id?: string | null;
}

/**
 * Request payload for creating a tax rate
 */
/**
 * Request payload for creating a tax rate
 */
export interface CreateTaxRateRequest {
  name: string;
  rate: number;
  description?: string;
  // sequence_no removed - now auto-generated by the system
  is_default?: boolean;
}

/**
 * Request payload for updating a tax rate
 */
export interface UpdateTaxRateRequest {
  name?: string;
  rate?: number;
  description?: string;
  // sequence_no removed - cannot be updated
  is_default?: boolean;
}

/**
 * Tax rate validation result
 */
export interface TaxRateValidation {
  isValid: boolean;
  errors: string[];
  warnings?: string[];
}

/**
 * Tax settings validation result
 */
export interface TaxSettingsValidation {
  isValid: boolean;
  errors: string[];
  warnings?: string[];
}

/**
 * Tax operation result
 */
export interface TaxOperationResult {
  success: boolean;
  data?: any;
  error?: string;
  message?: string;
}

/**
 * Tax rate summary for UI display
 */
export interface TaxRateSummary {
  id: string;
  name: string;
  rate: number;
  is_default: boolean;
  is_active: boolean;
  sequence_no: number;
}

/**
 * Tax configuration summary
 */
export interface TaxConfigSummary {
  display_mode: 'including_tax' | 'excluding_tax' | 'no_tax';
  default_rate_name: string | null;
  total_active_rates: number;
  has_default_rate: boolean;
}

/**
 * Audit metadata for tax operations
 */
export interface TaxAuditMetadata {
  operation: string;
  entity_type: 'settings' | 'rate';
  entity_id?: string;
  changes?: Record<string, any>;
  old_values?: Record<string, any>;
  new_values?: Record<string, any>;
  validation_errors?: string[];
  tenant_id: string;
  user_id?: string;
}

/**
 * Database field mappings for tax settings
 */
export interface TaxSettingsDbFields {
  id: string;
  tenant_id: string;
  display_mode: string;
  default_tax_rate_id: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

/**
 * Database field mappings for tax rates
 */
export interface TaxRateDbFields {
  id: string;
  tenant_id: string;
  name: string;
  rate: number;
  is_default: boolean;
  is_active: boolean;
  sequence_no: number;
  description: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

/**
 * Tax calculation context (for future use)
 */
export interface TaxCalculationContext {
  amount: number;
  tax_rate_id?: string;
  use_default_rate?: boolean;
  display_mode?: 'including_tax' | 'excluding_tax' | 'no_tax';
}

/**
 * Tax calculation result (for future use)
 */
export interface TaxCalculationResult {
  base_amount: number;
  tax_amount: number;
  total_amount: number;
  tax_rate: number;
  tax_rate_name: string;
  display_mode: 'including_tax' | 'excluding_tax' | 'no_tax';
}

/**
 * Constants for tax functionality
 */
export const TAX_CONSTANTS = {
  DISPLAY_MODES: {
    INCLUDING_TAX: 'including_tax' as const,
    EXCLUDING_TAX: 'excluding_tax' as const,
    NO_TAX: 'no_tax' as const,
  },
  VALIDATION: {
    MIN_RATE: 0,
    MAX_RATE: 100,
    MAX_NAME_LENGTH: 100,
    MAX_DESCRIPTION_LENGTH: 500,
    MIN_SEQUENCE: 1,
    MAX_SEQUENCE: 9999,
  },
  DEFAULTS: {
    DISPLAY_MODE: 'excluding_tax' as const,
    VERSION: 1,
    IS_ACTIVE: true,
    IS_DEFAULT: false,
  },
} as const;

/**
 * Tax error codes for consistent error handling
 */
export enum TaxErrorCode {
  // Validation errors
  INVALID_DISPLAY_MODE = 'INVALID_DISPLAY_MODE',
  INVALID_RATE_VALUE = 'INVALID_RATE_VALUE',
  INVALID_SEQUENCE_NUMBER = 'INVALID_SEQUENCE_NUMBER',
  NAME_REQUIRED = 'NAME_REQUIRED',
  NAME_TOO_LONG = 'NAME_TOO_LONG',
  DESCRIPTION_TOO_LONG = 'DESCRIPTION_TOO_LONG',
  VALIDATION_ERROR = 'VALIDATION_ERROR', // Add this
  
  // Business rule errors
  DUPLICATE_NAME = 'DUPLICATE_NAME',
  DUPLICATE_SEQUENCE = 'DUPLICATE_SEQUENCE',
  RATE_NOT_FOUND = 'RATE_NOT_FOUND',
  SETTINGS_NOT_FOUND = 'SETTINGS_NOT_FOUND',
  CANNOT_DELETE_DEFAULT_RATE = 'CANNOT_DELETE_DEFAULT_RATE',
  CANNOT_DELETE_ACTIVE_RATE = 'CANNOT_DELETE_ACTIVE_RATE',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION', // Add this
  
  // Concurrency errors
  VERSION_CONFLICT = 'VERSION_CONFLICT',
  OPTIMISTIC_LOCK_FAILURE = 'OPTIMISTIC_LOCK_FAILURE',
  
  // System errors
  DATABASE_ERROR = 'DATABASE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

/**
 * Tax error messages for user display
 */
export const TAX_ERROR_MESSAGES: Record<TaxErrorCode, string> = {
  [TaxErrorCode.INVALID_DISPLAY_MODE]: 'Display mode must be "including_tax", "excluding_tax", or "no_tax"',
  [TaxErrorCode.INVALID_RATE_VALUE]: 'Tax rate must be between 0 and 100',
  [TaxErrorCode.INVALID_SEQUENCE_NUMBER]: 'Sequence number must be a positive integer',
  [TaxErrorCode.NAME_REQUIRED]: 'Tax rate name is required',
  [TaxErrorCode.NAME_TOO_LONG]: 'Tax rate name cannot exceed 100 characters',
  [TaxErrorCode.DESCRIPTION_TOO_LONG]: 'Description cannot exceed 500 characters',
  [TaxErrorCode.VALIDATION_ERROR]: 'Validation failed', // Add this
  [TaxErrorCode.DUPLICATE_NAME]: 'A tax rate with this name already exists',
  [TaxErrorCode.DUPLICATE_SEQUENCE]: 'A tax rate with this sequence number already exists',
  [TaxErrorCode.RATE_NOT_FOUND]: 'Tax rate not found',
  [TaxErrorCode.SETTINGS_NOT_FOUND]: 'Tax settings not found',
  [TaxErrorCode.CANNOT_DELETE_DEFAULT_RATE]: 'Cannot delete the default tax rate',
  [TaxErrorCode.CANNOT_DELETE_ACTIVE_RATE]: 'Cannot delete an active tax rate',
  [TaxErrorCode.BUSINESS_RULE_VIOLATION]: 'Business rule violation', // Add this
  [TaxErrorCode.VERSION_CONFLICT]: 'The record was modified by another user. Please refresh and try again.',
  [TaxErrorCode.OPTIMISTIC_LOCK_FAILURE]: 'The record was modified by another user. Please refresh and try again.',
  [TaxErrorCode.DATABASE_ERROR]: 'Database operation failed',
  [TaxErrorCode.NETWORK_ERROR]: 'Network connection error',
  [TaxErrorCode.UNAUTHORIZED]: 'Authentication required',
  [TaxErrorCode.FORBIDDEN]: 'Insufficient permissions',
  [TaxErrorCode.INTERNAL_ERROR]: 'Internal server error',
};
/**
 * Type guards for runtime type checking
 */
export const TaxTypeGuards = {
  isTaxSettings: (obj: any): obj is TaxSettings => {
    return obj && 
           typeof obj.id === 'string' &&
           typeof obj.tenant_id === 'string' &&
           ['including_tax', 'excluding_tax', 'no_tax'].includes(obj.display_mode) &&
           typeof obj.version === 'number';
  },
  
  isTaxRate: (obj: any): obj is TaxRate => {
    return obj &&
           typeof obj.id === 'string' &&
           typeof obj.tenant_id === 'string' &&
           typeof obj.name === 'string' &&
           typeof obj.rate === 'number' &&
           typeof obj.is_active === 'boolean' &&
           typeof obj.version === 'number';
  },
  
  isValidDisplayMode: (mode: any): mode is 'including_tax' | 'excluding_tax' | 'no_tax' => {
    return mode === 'including_tax' || mode === 'excluding_tax' || mode === 'no_tax';
  },
  
  isValidRate: (rate: any): rate is number => {
    return typeof rate === 'number' && 
           rate >= TAX_CONSTANTS.VALIDATION.MIN_RATE && 
           rate <= TAX_CONSTANTS.VALIDATION.MAX_RATE;
  },
};

/**
 * Utility functions for tax operations
 */
export const TaxUtils = {
  /**
   * Validate tax rate data
   */
  validateTaxRate: (data: CreateTaxRateRequest | UpdateTaxRateRequest): TaxRateValidation => {
    const errors: string[] = [];
    
    if ('name' in data && data.name !== undefined) {
      if (!data.name || data.name.trim().length === 0) {
        errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.NAME_REQUIRED]);
      } else if (data.name.length > TAX_CONSTANTS.VALIDATION.MAX_NAME_LENGTH) {
        errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.NAME_TOO_LONG]);
      }
    }
    
    if ('rate' in data && data.rate !== undefined) {
      if (!TaxTypeGuards.isValidRate(data.rate)) {
        errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.INVALID_RATE_VALUE]);
      }
    }
    
    if ('sequence_no' in data && data.sequence_no !== undefined) {
      if (typeof data.sequence_no !== 'number' || 
          data.sequence_no < TAX_CONSTANTS.VALIDATION.MIN_SEQUENCE ||
          data.sequence_no > TAX_CONSTANTS.VALIDATION.MAX_SEQUENCE) {
        errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.INVALID_SEQUENCE_NUMBER]);
      }
    }
    
    if ('description' in data && data.description !== undefined && data.description) {
      if (data.description.length > TAX_CONSTANTS.VALIDATION.MAX_DESCRIPTION_LENGTH) {
        errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.DESCRIPTION_TOO_LONG]);
      }
    }
    
    return {
      isValid: errors.length === 0,
      errors,
    };
  },
  
  /**
   * Validate tax settings data
   */
  validateTaxSettings: (data: TaxSettingsRequest): TaxSettingsValidation => {
    const errors: string[] = [];
    
    if (!TaxTypeGuards.isValidDisplayMode(data.display_mode)) {
      errors.push(TAX_ERROR_MESSAGES[TaxErrorCode.INVALID_DISPLAY_MODE]);
    }
    
    return {
      isValid: errors.length === 0,
      errors,
    };
  },
  
  /**
   * Get next sequence number
   */
  getNextSequence: (existingRates: TaxRate[]): number => {
    if (existingRates.length === 0) return 1;
    
    const maxSequence = Math.max(...existingRates.map(r => r.sequence_no));
    return maxSequence + 1;
  },
  
  /**
   * Sort tax rates by sequence
   */
  sortBySequence: (rates: TaxRate[]): TaxRate[] => {
    return [...rates].sort((a, b) => {
      if (a.sequence_no === b.sequence_no) {
        return a.name.localeCompare(b.name);
      }
      return a.sequence_no - b.sequence_no;
    });
  },
  
  /**
   * Find default tax rate
   */
  findDefaultRate: (rates: TaxRate[]): TaxRate | null => {
    return rates.find(rate => rate.is_default && rate.is_active) || null;
  },
  
  /**
   * Create audit metadata
   */
  createAuditMetadata: (
    operation: string,
    entityType: 'settings' | 'rate',
    tenantId: string,
    entityId?: string,
    changes?: Record<string, any>,
    oldValues?: Record<string, any>
  ): TaxAuditMetadata => {
    return {
      operation,
      entity_type: entityType,
      entity_id: entityId,
      changes,
      old_values: oldValues,
      new_values: changes,
      tenant_id: tenantId,
    };
  },
};