-- ============================================================================
-- Migration: Group Session Chair Assignment — 030
-- ============================================================================
-- Purpose (Sprint 5+6 combined planning, 19 Jul 2026 — CORRECTION):
--   An earlier pass this session built a brand-new parallel table
--   (t_session_occurrence_assignments) + 2 RPCs to solve "one instructor
--   assigned once per Group Session occurrence, fanned to every member,"
--   reasoning from t_contract_events/t_appointments alone — WITHOUT first
--   searching for an existing Group Sessions backend. The owner then
--   showed a live, fully-built Group Sessions dashboard
--   (localhost:5173/group-sessions) running against Test data that the
--   earlier live-only DB queries had missed entirely.
--
--   Ground truth, found via pg_get_functiondef on the real gs_* RPC
--   family (bbb-foundation/021 onward): Group Session occurrences already
--   live in t_group_session_schedule — ONE row per (tenant, block, date),
--   generated by gs_generate_schedule() straight from the catalog block's
--   serviceCycles config, completely decoupled from t_contract_events
--   (member contracts carry the block via t_contract_blocks only — they
--   do NOT spawn one event per member, confirming the owner's instinct
--   that 50 events-on-a-date would be a mess and was correctly avoided).
--   Attendance already lives in t_session_attendance, keyed by
--   schedule_occurrence_id. Roster, QR check-in (self/guest/substitute),
--   dues-paid marking, and a full dashboard (gs_dash_sessions/
--   gs_dash_occurrences/gs_dash_roster/gs_dash_member) all already exist
--   and are live.
--
--   The ONE real gap: t_group_session_schedule had no column for who
--   chairs/hosts a given occurrence — exactly what the owner asked for
--   ("a Group Session is headed by someone... he will have an appointment
--   against 'Group Session' in the cadence"). This migration adds that,
--   and ONLY that, directly onto the existing table — no new parallel
--   entity, reusing gs_dash_occurrences/QR/roster/attendance untouched.
--
--   The earlier redundant table + 2 RPCs were dropped live before this
--   file was written (0 rows ever existed in the table, 0 dependents —
--   confirmed before dropping). This file replaces that batch entirely;
--   see COPY_INSTRUCTIONS.txt for the full correction trail.
-- Depends on: bbb-foundation/021 (t_group_session_schedule)
-- Safe to re-run: Yes
-- Applied by: OWNER — project uwyqhzotluikawcboldr
-- ============================================================================

ALTER TABLE t_group_session_schedule
  ADD COLUMN IF NOT EXISTS assigned_to UUID,
  ADD COLUMN IF NOT EXISTS assigned_to_name TEXT;

-- gs_dash_occurrences: additive — assigned_to/assigned_to_name added to the
-- per-occurrence payload. Everything else reproduced VERBATIM from the live
-- definition (pulled via pg_get_functiondef).
CREATE OR REPLACE FUNCTION public.gs_dash_occurrences(p_tenant uuid, p_block uuid, p_is_live boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v jsonb; v_total int;
BEGIN
  SELECT count(*) INTO v_total FROM t_group_session_schedule
   WHERE tenant_id=p_tenant AND source_block_id=p_block AND is_live=p_is_live AND status<>'cancelled';
  SELECT coalesce(jsonb_agg(r ORDER BY (r->>'date')), '[]'::jsonb) INTO v FROM (
    SELECT jsonb_build_object('event_id', s.id, 'date', s.occurrence_date, 'seq', s.seq, 'total', v_total,
      'status', s.status, 'is_past', s.occurrence_date < current_date, 'note', s.note,
      'assigned_to', s.assigned_to, 'assigned_to_name', s.assigned_to_name,
      'present', (SELECT count(*) FROM t_session_attendance a WHERE a.schedule_occurrence_id=s.id AND a.status='present')) AS r
    FROM t_group_session_schedule s WHERE s.tenant_id=p_tenant AND s.source_block_id=p_block AND s.is_live=p_is_live
  ) x;
  RETURN jsonb_build_object('occurrences', v);
END $function$;

-- New RPC, matching the gs_schedule_status/gs_schedule_move convention
-- exactly (same {ok:false, reason:'not_found'} error shape, same
-- "return the refreshed occurrence list" success shape, no exception
-- wrapper — this family doesn't use one).
CREATE OR REPLACE FUNCTION public.gs_schedule_assign(p_tenant uuid, p_id uuid, p_assigned_to uuid, p_assigned_to_name text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_block uuid; v_live boolean;
BEGIN
  SELECT source_block_id, is_live INTO v_block, v_live
  FROM t_group_session_schedule WHERE id=p_id AND tenant_id=p_tenant;
  IF v_block IS NULL THEN RETURN jsonb_build_object('ok', false, 'reason', 'not_found'); END IF;
  UPDATE t_group_session_schedule
    SET assigned_to=p_assigned_to, assigned_to_name=p_assigned_to_name, updated_at=now()
  WHERE id=p_id AND tenant_id=p_tenant;
  RETURN gs_dash_occurrences(p_tenant, v_block, v_live);
END $function$;

-- ─────────────────────────────────────────────
-- Revert of the earlier (wrong-turn) migration — for the record only;
-- already executed live before this file was written.
-- ─────────────────────────────────────────────
-- DROP FUNCTION IF EXISTS assign_session_occurrence(UUID, TEXT, DATE, UUID, TEXT, BOOLEAN, UUID, TEXT);
-- DROP FUNCTION IF EXISTS get_session_occurrences(UUID, BOOLEAN, DATE, DATE);
-- DROP TABLE IF EXISTS t_session_occurrence_assignments;
